In [ ]:
## 1. Take values of the length & breadth of a rectangle from user input and check if it is square or not.

n1=input("Enter Length \n")

n2=input("Enter Breadth \n")

if n1==n2:
    print("square")
    
else:
    print("Rectangle but not a Square")

In [ ]:
# 2.Take three integer values from the user and print the greatest among them. 

n1=int(input("Enter First Value: \n"))


n2=int(input("Enter Second Value: \n"))

n3=int(input("Enter Third Value: \n"))

if (n1>n2) and (n1>n3):
    print(f'{n1} is the largest!')
    
elif (n2>n1) and (n2>n3):
    print(f'{n2} is the largest!')
    
else:
    print(f'{n3} is the largest!')

In [ ]:
## 3.A student will not be allowed to sit in an exam if his/her attendance is less than 75%.

no_of_total_class=int(input("no of total classes: \n"))

no_of_attended_class=int(input("No of attended classes: \n"))

atd=((no_of_attended_class)*100)/no_of_total_class

print(f'Allowed to attend in Exam with a percentage of {atd}')

if atd<75:
    print('not allowed to attend in an exam')

In [ ]:
##  4.grading system for a school: 

num=int(input('Enter your marks: '))


if num>=90:
    print('A+')
    
elif num>=80 and num<=89:
    print('A')
    
elif num>=60 and num<=79:
    print('B')

elif num>=50 and num<=59:
    print('C')
    
elif num>=45 and num<=49:
    print('D')
    
elif num>=25 and num<=44:
    print('E')
    
elif num<25:
    print('F')

In [ ]:
## 5.Print the following pattern using for and while loop. 
#1 2 3 4 5 6 7 
#1 2 3 4 5 6 
#1 2 3 4 5 
#1 2 3 4 

n1=4

n=7

while n1>=1:
    
    n1=n1-1
    
    for x in range(1,n+1):
        print(x,end = " ")
        
        
    print("\n")
    
    
    n=n-1

In [ ]:
### 6.Display numbers from -100 to -10 using for loop. 

for i in range(-100,-10+1):

     print(i,end = "  ")

In [ ]:
## 7. Write a program to sum all prime numbers within a range of 10 to 1000. 

import math

s=0

for i in range(10,1000+1):
    
    
    n=math.sqrt(i)
    n=int(n)
    
    f=0
    
    for j in range(2,n+2):
        
        if i%j==0:
            f=1
            break
            
    if f==0:
        s=s+i
        
print(s)

In [ ]:
## 8.Find the factorial of an n! (Hint, n=7: 7*6*5*4*3*2*1).

n=int(input("Enter a number:"))

i=1

for j in range(1,n+1):
    
    i=j*i
    
print(i)

In [ ]:
###  9. Reverse a given integer number 27956240710. 

n=27956240710

s=''


while n!=0:
    
    r=n%10
    
    n=n//10
    
    r1=str(r)
    
    s=s+r1
    
s1=''


for i in range(1,len(s)):
    
    s2=s[i]
    
    s1=s1+s2
    

    
print(s1)

In [ ]:
## 10. Print the following pattern using for and while loop.

print('# # #')

i=4

while i>=2:
    
    for j in range (i):
        
        print('# ',end="")
    print()
    
    i=i-1

In [ ]:
### 11. Display the Fibonacci series of 15 elements using the for and while loop.


n1=0
n2=1

print(n1,n2,end=" ")

n=15

for i in range(3,16):
    
    n3=n1+n2
    
    print(n3,end=" ")
    
    n1=n2
    n2=n3

In [ ]:
##Python inbuilt Data Structure:

## 12. Remove 2 and add 3 to the list and replace True with False.
#Li = [1,3,5, [2,3], True]


li = [1,3,5, [2,3], True]


for i in range(len(li)-1):
    
    s=str(li[i])
    
    if len(s)>1:
        
        k2=i
        k3=0
        
        for k1 in range(len(li[i])):
            
            if li[k2][k3]==2:
                
                li[k2][k3]=3
                
            k3+=1
            
            
for i in range(len(li)):
    
    x=type(li[i])
    
    if x==int:
        continue
        
    else:
    
        if li[i]==True:

            li[i]=False
            
print(li)

In [ ]:
## 13.Find the intersection (common) of two sets.


s1 = ({1,4,6,8})
s2 = { True,1,2,10}

s = s1 & s2

print(s)

In [ ]:
## 14. Input a list from the user then Remove duplicates from a list and create a set and find the max number.

##User_input = [1,9,3,4,5,200,54]


element_list = []

list_length = 7

for idx in range(list_length):
    item = input('Enter Elements: ')
    element_list.append(item)
    
ints_list1 = (set(element_list))


##ints_list1=list(ints_list1)

print(ints_list1)

print(max(ints_list1))

In [ ]:
## 15. Rename the key of a dictionary.


Dict = { "name": "Shakil", "age":27, "city": 'Berlin', "country": "Germany" }

D={}

for key,value in Dict.items():
    
    if key=='country':
        
        D['region']=value
        
    else:
        
        D[key]=value
        
del  Dict

Dict=D

print(Dict)

In [1]:
## 16. Creating a data frame using the list.

import pandas as pd

num = [10,100,300]

df=pd.DataFrame(num,columns=["number"])

print(df)

   number
0      10
1     100
2     300

In [2]:
## 17. Change the value of a key in a given dictionary.

#Write a Python program to change ‘age’ to 28 in the following dictionary.


Dict = { "name": "Shakil", "age":27, "city": 'Berlin', "country": "Germany"}


D={}

for k,v in Dict.items():
    
    if k=='age':
        
        D['age']=28
        
    else:
        
        D[k]=v
        
        
        
Dict=D

print(Dict)

{'name': 'Shakil', 'age': 28, 'city': 'Berlin', 'country': 'Germany'}